### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by flashwave** [flashwave/whois-php#1]
- [x] Clean up the code.
- [x] Make directory structure PSR-4 compliant.
- [x] Create a composer package.
